### ISSUE TITLE
Redis not configurable from env

### ISSUE THREAD

**Issue by gaelreyrol** [codidact/qpixel#579]
Redis is configurable with the `config/database.yml` file but environment variables are not injected.
It throws an error when trying to connect to the redis server:
```
Redis::CannotConnectError (Error connecting to Redis on <%= ENV["REDIS_HOST"] %>:0 (SocketError)):
```
I think it comes from the way this `config/database.yml` file is loaded in [request_context.rb](https://github.com/codidact/qpixel/blob/develop/app/models/request_context.rb#L12).

I am not a Rubyist but I think it needs to be interpreted as an **ERB** file like in this [file](https://github.com/codidact/qpixel/blob/develop/config/initializers/config.rb#L6).

**To Reproduce**
Configure redis settings in `config/database.yml` like so:
```yaml
redis_default: &redis_default
  host: <%= ENV["REDIS_HOST"] %>
  port: <%= ENV["REDIS_PORT"] %>
  password: <%= ENV["REDIS_PASSWORD"] %>
```
